version: 2

models:
  - name: stg_superheroes
    description: Demographics about each superhero such as name, hair color, height and weight. 
    columns:
    - name: name
      tests:
        - not_null
    - name: height
      tests:
        - positive_values
    - name: weight
      tests:
        - positive_values
  
  - name: stg_addresses
    description: addresses 
    columns:
      - name: address_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: zipcode
        tests:
          -positive_values

  - name: stg_events
    description: digital actions taken on websites
    columns:
      - name: event_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: stg_order_items
    description: items ordered
    columns:
      - name: order_id
        description: "The primary key for this table"
        tests:
          - not_null

  - name: stg_orders
    description: orders and status of delivery
    columns:
      - name: order_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: order_cost
        tests:
          - not_null
          - positive_values 
      - name: order_total
        tests:
          - not_null
          - positive_values

  - name: stg_products
    description: products and quantity 
    columns:
      - name: product_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: stg_promos
    description: promos and their status
    columns:
      - name: promo_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
            values: ['inactive','active'] 
          

  - name: stg_users
    description: users and their contact info
    columns:
      - name: user_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null